In [10]:
import torch
global_proto = torch.load('global_proto_best.pth')
print(global_proto.shape)
for i,proto in enumerate( global_proto):
    if i<101:
        print(proto)

(600, 1600)
[0.15520892 0.1367066  0.1382314  ... 0.26283879 0.27631332 0.28275588]
[0.13960843 0.14834055 0.15410993 ... 0.18894674 0.18779206 0.17635406]
[0.12183195 0.11015103 0.11511047 ... 0.18842539 0.18711064 0.17304169]
[0.19659172 0.20319003 0.20940369 ... 0.40009893 0.3814516  0.37690136]
[0.17959775 0.17307155 0.17381281 ... 0.23483294 0.22900176 0.24454871]
[0.1601887  0.14760402 0.14963886 ... 0.27426211 0.26809856 0.24666703]
[0.28719241 0.25028238 0.25487954 ... 0.12991937 0.14067181 0.16304   ]
[0.50153866 0.43759554 0.43167883 ... 0.15812391 0.15538999 0.17813238]
[0.14523098 0.14267984 0.14378183 ... 0.10747067 0.11069697 0.10885372]
[0.16182561 0.14151369 0.14315204 ... 0.12831595 0.1327947  0.14230091]
[0.15499488 0.20535015 0.22468169 ... 0.111894   0.12759273 0.11443908]
[0.1898205  0.1496282  0.15826268 ... 0.06961671 0.07242801 0.10031148]
[0.1995012  0.18975578 0.18399824 ... 0.15768647 0.15778538 0.16798517]
[0.30465903 0.45003911 0.47228609 ... 0.21985397 0.2